name: Build and Publish Base Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "package-lock.json" # Only run when package-lock.json changes
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  publish-base-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.base
          tags: ghcr.io/${{ github.repository }}/nextjs-docker-base:latest
